export const blogsection = {
  container: {
    width: "90%",
    margin: "2rem auto",
    "@media(max-width: 768px)": {
      width: "100%",
    },
  },
  topcontemttext: {
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
    alignItems: "center",
    gap: "1rem",
    "@media(max-width: 768px)": {
      gap: "0.5rem",
    },
  },
  header: {
    color: "#6D9E3F",
    fontWeight: "700",
    fontFamily: "DM Sans",
    fontSize: "1rem",
    lineHeight: "2rem",
    textTransform: "uppercase",
    // "@media(max-width: 768px)": {},
  },
  header2: {
    color: "black",
    fontWeight: "700",
    fontFamily: "DM Sans",
    fontSize: "1.75rem",
    lineHeight: "3rem",
    textTransform: "capitalize",
    textAlign: "center",
    "@media(max-width: 768px)": {
      lineHeight: "2.5rem",
      fontSize: "1.5rem",
      textAlign: "center",
    },
    "@media(max-width: 600px)": {
      lineHeight: "2rem",
      fontSize: "1.2rem",
    },
  },
  listContainer: {
    display: "flex",
    gap: "2vw",
    margin: "2vw auto",
    width: "100%",
    "@media(max-width: 768px)": {
      overflowX: "auto",
      flexWrap: "nowrap",
      margin: "4vw 4vw 4vw 5vw",
    },
    "&::-webkit-scrollbar": {
      display: "none",
    },
  },
  listContainerblog: {
    display: "flex",
    gap: "2.5rem",
    margin: "2rem auto",
    justifyContent: "flex-start",
    width: "100%",
    "@media(max-width: 768px)": {
      overflowX: "auto",
      flexWrap: "nowrap",
      paddingLeft: "2rem",
    },
    "&::-webkit-scrollbar": {
      display: "none",
    },
  },
  card: {
    width: "33.333%",
    boxShadow: "0",
    borderRadius: "8px",
    border: "1px solid rgba(234, 234, 234, 1)",
    // flex: "1",
    "@media(max-width: 768px)": {
      minWidth: "35%",
    },
    "@media(max-width: 600px)": {
      minWidth: "60%",
    },
  },
  cardblog: {
    width: "33%",
    boxShadow: "0",
    borderRadius: "8px",
    "@media(max-width: 768px)": {
      minWidth: "60%",
    },
    "@media(max-width: 600px)": {
      minWidth: "80%",
    },
  },
  carddetails: {
    display: "flex",
    justifyContent: "flex-start",
    alignItems: "flex-start",
    flexDirection: "column",
    gap: ".8vw",
    padding: "2vw 2vw",
    background: "white",
    "@media(max-width: 768px)": {
      gap: "2vw",
    },
  },
  carddetailsBlog: {
    display: "flex",
    justifyContent: "flex-start",
    alignItems: "flex-start",
    flexDirection: "column",
    gap: "1rem",
    background: "white",
    padding: "0.5rem 0",
    "@media(max-width: 768px)": {
      gap: "0.5rem",
      padding: "0.3rem 0",
    },
  },
  details: {
    display: "flex",
    justifyContent: "flex-start",
    alignItems: "center",
    gap: ".5rem",
    color: "#686868",
    flexWrap: "wrap",
  },
  topic: {
    color: "#003C1C",
    fontWeight: "700",
    fontFamily: "DM Sans",
    fontSize: "1.25rem",
    lineHeight: "2rem",
    textTransform: "capitalize",
    "@media(max-width: 768px)": {
      fontSize: "1rem",
      lineHeight: "1.5rem",
    },
  },
  topicuserdets: {
    color: "#686868",
    fontWeight: "400",
    fontFamily: "DM Sans",
    fontSize: "1rem",
    lineHeight: "1.54rem",
    textTransform: "capitalize",
    // "@media(max-width: 600px)": {
    //   fontSize: "0.8rem",
    //   lineHeight: "1.1rem",
    // },
  },
  readmore: {
    color: "#6D9E3F",
    fontWeight: "700",
    fontFamily: "DM Sans",
    fontSize: "1rem",
    lineHeight: "1.67rem",
    textTransform: "capitalize",
    cursor: "pointer",
  },
  excerpt: {
    color: "#686868",
    fontWeight: "400",
    fontFamily: "DM Sans",
    fontSize: "1rem",
    lineHeight: "1.67rem",
    // textAlign: "center",
  },
  viewmoreButton: {
    color: "white",
    backgroundColor: "#006D33",
    fontWeight: "500",
    fontFamily: "DM Sans",
    fontSize: "1rem",
    width: "18rem",
    height: "3.8rem",
    borderRadius: "4px",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    margin: "0 auto",
    textAlign: "center",
    textDecoration: "none",
    transition: "background transform 1s ease",
    textTransform: "capitalize",
    "&:hover": {
      background: "#003C1C",
    },
    "@media (max-width: 768px)": {
      width: "9rem",
      height: "2.8rem",
      fontSize: "0.8rem",
    },
  },
  usericon: {
    "@media(max-width: 768px)": {
      width: "3%",
    },
  },
  readmorearrow: {
    width: "20%",
  },
  blogdetails: {
    "@media(max-width: 768px)": {
      display: "flex",
      flexDirection: "column",
      gap: "3vw",
    },
  },
};
